# Base the image off of the Ubuntu 18.04 image from Dockerhub

# Set the Maintainer label to your name.

# Install python3 and python3-pip via apt

# Install flask, flask-wtf and redis via pip3

# Create the flask directory /app

# Copy in the flask application in ./app into /app in the image.

# Set /app as the working directory

# Set the LC_ALL environment variable to C.UTF-8.

# Set the LANG environment variable to C.UTF-8.

# Set the FLASK_APP environment variable to guestbook.py

# Expose port 5000 for Flask.

# Set the entrypoint to python3 -m flask

# Set the command to run run and be sure to include the option --host=0.0.0.0
