# Use Ubuntu 18.04 as the base image.
FROM ubuntu:18.04

# Set our entrypoint to the echo binary and set the standard arguments to echo.
ENTRYPOINT [ "echo", "Hello", "there," ]

# Set the default command for the image. We can override this when we run
# a container based on this image.
CMD [ "friend" ]